# fly.toml app configuration file generated for dom-embedding-right on 2023-07-29T14:26:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dom-embedding-right"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
