# fly.toml app configuration file generated for patient-brook-9057 on 2023-07-29T17:49:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-brook-9057"
primary_region = "sea"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[services.resources]
memory = "4096Mi"